### ISSUE TITLE
Cannot access non-https resources from Github pages?

### ISSUE THREAD

**Issue by ejaxon** [cityofasheville/Civic_Programmer_Analyst_Skills_Task#7]
![screen shot 2016-07-26 at 10 23 56 am](https://cloud.githubusercontent.com/assets/6409214/17141698/2277905c-531b-11e6-945e-b83b749fc033.png)
I may be misunderstanding something, but it looks like Github pages requires use of https, but that then doesn't allow me to load resources (i.e., the REST API) over http. Appears neither of the ArcGIS servers respond to https. I have to either find a REST endpoint that supports https access or host on something other than Github pages.

Am I missing something? If not, are there secure versions of the ArcGIS endpoints?

**Comment by ejaxon** [comment]
You can ignore this if you like. I've just gone with hosting elsewhere.

**Comment by carlyleec** [comment]
So guess GitHub just switched last month to requiring HTTPS for all GitHub pages, which is a good thing. I didn't know that till now. We're getting around it with SimpliCity because we have a HTTP CNAME configured for that repo. Incidentally, the original API we provided through the Open Data Portal can be accessed via HTTPS; however the alternate API I provided that is used by SimpliCity is only configured for HTTP. Sorry guys!
